framework:
    cache:
        pools:
            cache.openapivalidator:
                adapter: cache.adapter.filesystem # TODO: substitute with a real cache, even APCu is fine
                default_lifetime: 0
