monolog:
    channels: [deprecation]
    handlers:
        deprecation:
            type: stream
            channels: [deprecation]
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
